# Header
menu:
  首页: /
  归档: /archives
rss: /atom.xml

# Content
excerpt_link: 继续阅读全文 »
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- recent_posts
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
# 若使用多说，此处填写的是多说评论账号ID
# 若使用Disqus，请在博客 config 文件中填写disqus_shortname，并设置duosuo: false关闭多说评论
duoshuo_shortname: false
google_plus:
fb_admins:
fb_app_id:
